import { baseTemplate } from "../base";
import ImageCss from "./ImageCss.js";
const handlebars = require("handlebars");

const buildUnsplashUrl = ({ unsplashId, unsplashKeywords, size }) => {
  const baseUrl = "https://source.unsplash.com";
  const sizeStr = `${size.width}x${size.height}`;

  if (unsplashId) {
    return `${baseUrl}/${unsplashId}/${sizeStr}`;
  } else if (unsplashKeywords) {
    return `${baseUrl}/${sizeStr}?${unsplashKeywords}`;
  }

  throw new Error("No ID or keywords specified for unsplash URL");
};

export const basicTemplate = handlebars.compile(`
<div class="Main">
  {{#if backgroundImageUrl}}<div class="Background">
    <div
      class="Image Image--cover Image--anchor{{backgroundImageAnchor}}  {{#if backgroundImageOverlay}}Image--overlay Image--dark{{/if}}">
      <img class="Image-img" src="{{backgroundImageUrl}}" />
    </div>
  </div>{{/if}}
  <div class="Inner">
    {{title}}
  </div>
  {{#if includeWatermark}}
  <div class="Watermark">
    {{#if watermarkUrl}}Generated by <span class="Watermark-logo">{{watermarkUrl}}</span>{{/if}}
    {{#if watermark}}{{watermark}}{{/if}}
  </div>{{/if}}
</div>
`);

const buildStyles = ({
  background = "black",
  backgroundImageUrl,
  color = "white",
  fontFamily = '"Avenir Next", "Lato", "Helvetica Neue", sans-serif',
  fontSize = "128px",
  fontWeight = "700"
} = {}) => `
.Background {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
}

${ImageCss};

.Main {
  background: ${backgroundImageUrl ? "transparent" : background};
  position: relative;
  width: 100%;
  height: 100%;
  z-index: -2;
}

.Inner {
  align-items: center;
  background: ${backgroundImageUrl ? "transparent" : background};
  color: ${color};
  display: flex;
  justify-content: center;
  font-family: ${fontFamily};
  font-size: ${fontSize};
  font-weight: ${fontWeight};
  line-height: 1.2;
  padding: 32px;
  text-align: center;
  width: 100%;
  height: 100%;
}

.Watermark {
  color: white;
  font-family: ${fontFamily};
  font-size: 24px;
  position: absolute;
  opacity: 0.8;
  right: 8px;
  bottom: 8px;
}

.Watermark-logo {
  font-weight: 900;
}
`;

export default ({
  size,
  templateParams: {
    gradient = true,
    imageUrl,
    unsplashId,
    unsplashKeywords,
    ...templateParams
  }
}) => {
  let backgroundImageUrl;

  if (imageUrl) {
    backgroundImageUrl = imageUrl;
  } else if (unsplashId) {
    backgroundImageUrl = buildUnsplashUrl({ unsplashId, size });
  } else if (unsplashKeywords) {
    backgroundImageUrl = buildUnsplashUrl({ unsplashKeywords, size });
  }

  return baseTemplate({
    body: basicTemplate({
      backgroundImageAnchor: "C",
      backgroundImageOverlay: gradient,
      backgroundImageUrl,
      includeWatermark:
        templateParams.watermarkUrl || templateParams.watermark || false,
      ...templateParams
    }),
    height: size.height,
    styles: buildStyles({ backgroundImageUrl, ...templateParams }),
    width: size.width
  });
};
